## Import

In [1]:
from tqdm import tqdm

import FinanceDataReader as fdr
import numpy as np
import pandas as pd
import re

* america

In [2]:
df_nyse = fdr.StockListing('NYSE')   # 뉴욕거래소
df_nasdaq = fdr.StockListing('NASDAQ') # 나스닥
df_amex = fdr.StockListing('AMEX')   # 아멕스

100%|█████████████████████████████████████████████████████████████████████████████| 3459/3459 [00:04<00:00, 703.26it/s]
100%|█████████████████████████████████████████████████████████████████████████████| 4547/4547 [00:07<00:00, 613.03it/s]
100%|███████████████████████████████████████████████████████████████████████████████| 306/306 [00:00<00:00, 811.74it/s]

* china, japan

In [3]:
df_sse = fdr.StockListing('SSE')
df_szse = fdr.StockListing('SZSE')
df_hkex = fdr.StockListing('HKEX')
df_tse = fdr.StockListing('TSE')

100%|█████████████████████████████████████████████████████████████████████████████| 1033/1033 [00:01<00:00, 763.84it/s]
100%|█████████████████████████████████████████████████████████████████████████████| 1424/1424 [00:01<00:00, 750.76it/s]
100%|█████████████████████████████████████████████████████████████████████████████| 2645/2645 [00:04<00:00, 629.93it/s]
100%|█████████████████████████████████████████████████████████████████████████████| 3928/3928 [00:07<00:00, 560.08it/s]

In [7]:
tot_df = pd.concat([df_nyse, df_nasdaq, df_amex, df_sse, df_szse, df_hkex, df_tse], axis =0)
tot_df.drop_duplicates(inplace = True)
tot_df.shape

In [8]:
tot_df.head()

,Symbol,Name,Industry,IndustryCode
0,TSM,Taiwan Semiconductor Manufacturing Co Ltd ADR,반도체 및 반도체 장비,571010
1,V,Visa Inc Class A,소프트웨어 및 IT서비스,572010
2,JPM,JPMorgan Chase & Co,은행,551010
3,UNH,UnitedHealth Group Inc,헬스케어 업체 및 서비스,561020
4,JNJ,Johnson & Johnson,제약,562010

* theme df

In [9]:
data_path = "C:\\Users\\PC0\\Documents\\datasets\\"

In [10]:
df_theme = pd.read_csv(data_path + 'sector.csv', encoding = "cp949")
df_theme = df_theme.dropna()

In [11]:
df_theme.head()

          테마    해당 주식  종목코드
0  빅테크-A(미국)       애플  AAPL
1  빅테크-A(미국)      알파벳  GOOG
2  빅테크-A(미국)       메타    FB
3  빅테크-A(미국)  마이크로소프트  MSFT
4  빅테크-A(미국)      아마존  AMZN

* 테마별 종목 확인

In [12]:
theme_list = df_theme.테마.unique()
theme_code = df_theme.loc[df_theme.테마 == theme_list[0]].종목코드

In [13]:
industry_list = tot_df.loc[tot_df.Symbol.isin(theme_code), 'Industry'].unique()

In [14]:
tot_df.loc[tot_df.Industry.isin(industry_list)].head()

,Symbol,Name,Industry,IndustryCode
0,TSM,Taiwan Semiconductor Manufacturing Co Ltd ADR,반도체 및 반도체 장비,571010
1,V,Visa Inc Class A,소프트웨어 및 IT서비스,572010
10,MA,Mastercard Inc Class A,소프트웨어 및 IT서비스,572010
12,BABA,Alibaba Group Holding Ltd ADR,소프트웨어 및 IT서비스,572010
17,TM,Toyota Motor Corp ADR,자동차 및 자동차 부품,531010

In [15]:
tot_df.loc[tot_df.Industry.isin(industry_list)].shape

(2574, 4)

* market cap

In [16]:
import pandas_datareader as pdr
import yfinance as yf

In [28]:
cnt = 0

In [29]:
for idx, code in tqdm(enumerate(tot_df.Symbol)):
    try :
        temp_df  = pdr.data.get_quote_yahoo(code)
    except :
        continue
        
    if cnt == 0:
        info_df = temp_df
        cnt += 1
    else :
        info_df = info_df.append(temp_df)

17334it [7:11:52,  1.49s/it]

In [32]:
info_df.to_csv("info_df.csv")

In [55]:
info_df.shape

(7432, 81)

In [54]:
info_df.loc[info_df.index.isin(theme_code), [x for x in (info_df.dtypes == np.float64)]].iloc[:,2:]

,postMarketTime,postMarketPrice,postMarketChange,regularMarketChange,regularMarketChangePercent,regularMarketPrice,regularMarketDayHigh,regularMarketDayLow,regularMarketVolume,regularMarketPreviousClose,...,twoHundredDayAverageChangePercent,marketCap,forwardPE,priceToBook,pageViewGrowthWeekly,price,earningsTimestamp,earningsTimestampStart,earningsTimestampEnd,openInterest
TSM,1.644887e+09,120.090,0.320000,-1.240006,-1.024713,119.77,121.5500,118.0000,7751888.0,121.01,...,0.012895,6.211272e+11,18.802198,0.286459,-0.152045,119.77,NaN,NaN,NaN,NaN
CRM,1.644887e+09,207.180,0.779999,-1.500000,-0.721501,206.40,209.9000,204.6300,6535766.0,207.90,...,-0.185861,2.033040e+11,43.636364,3.559725,-0.156307,206.40,1.646168e+09,1.646168e+09,1.646168e+09,NaN
AAPL,1.644873e+09,168.765,-0.115005,0.240006,0.142318,168.88,169.5714,166.5600,81601195.0,168.64,...,0.125140,2.770713e+12,27.326862,43.967716,NaN,168.88,1.635439e+09,1.650971e+09,1.651493e+09,NaN
MSFT,1.644873e+09,295.000,0.000000,-0.040009,-0.013560,295.00,296.7600,291.3500,36227831.0,295.04,...,-0.003162,2.214854e+12,27.988615,14.573658,NaN,295.00,1.635265e+09,1.650884e+09,1.651234e+09,NaN
AMZN,1.644873e+09,3104.655,1.314941,37.469970,1.222164,3103.34,3168.9663,3033.0000,3833280.0,3065.87,...,-0.076876,1.573853e+12,60.223950,13.050265,NaN,3103.34,1.635437e+09,1.651090e+09,1.651522e+09,NaN
TSLA,1.644873e+09,877.145,1.385010,15.760010,1.832559,875.76,898.8799,853.1500,22267816.0,860.00,...,0.062800,8.794907e+11,99.972600,32.501762,NaN,875.76,1.634746e+09,1.650917e+09,1.651262e+09,NaN
GOOG,1.644873e+09,2706.500,0.500000,23.399902,0.872284,2706.00,2723.3298,2666.2014,1256833.0,2682.60,...,-0.008172,1.796034e+12,24.096170,7.354340,NaN,2706.00,NaN,NaN,NaN,NaN
NVDA,1.644873e+09,243.110,0.440002,3.179993,1.327819,242.67,248.7500,237.5500,43433348.0,239.49,...,0.069193,6.047336e+11,46.577736,25.511984,NaN,242.67,1.637166e+09,1.645528e+09,1.646050e+09,NaN
FB,1.644873e+09,217.730,0.029999,-1.850006,-0.842635,217.70,221.0000,214.7900,38001320.0,219.55,...,-0.350161,6.055891e+11,15.298665,4.559353,NaN,217.70,1.635178e+09,1.650971e+09,1.651493e+09,NaN
AVGO,1.644873e+09,579.475,0.894958,5.160034,0.899870,578.58,582.8117,570.0700,1822865.0,573.42,...,0.112804,2.388806e+11,16.049377,9.572641,NaN,578.58,1.639067e+09,1.646219e+09,1.646654e+09,NaN
CSCO,1.644873e+09,53.360,0.180000,-0.720001,-1.335809,53.18,53.6500,52.7000,21444836.0,53.90,...,-0.050843,2.242925e+11,14.451087,5.251827,NaN,53.18,1.612887e+09,1.644232e+09,1.644581e+09,NaN
ADBE,1.644873e+09,474.205,0.194977,0.040009,0.008441,474.01,478.5700,469.2800,3243810.0,473.97,...,-0.193744,2.255340e+11,29.169847,15.248343,NaN,474.01,1.639652e+09,1.647860e+09,1.648210e+09,NaN
INTC,1.644873e+09,47.600,0.019997,-0.049999,-0.104974,47.58,48.1772,47.1101,27058800.0,47.63,...,-0.107905,1.935079e+11,12.859460,2.147985,NaN,47.58,1.634846e+09,1.650485e+09,1.650917e+09,NaN
QCOM,1.644873e+09,165.565,0.434998,0.490005,0.297622,165.13,167.8500,162.4800,8085140.0,164.64,...,0.092497,1.849456e+11,14.186426,18.671417,NaN,165.13,1.643836e+09,1.650971e+09,1.651493e+09,NaN
NFLX,1.644873e+09,396.785,0.214996,5.260010,1.344205,396.57,409.3400,386.8910,6963082.0,391.31,...,-0.286150,1.756615e+11,30.295647,11.470180,NaN,396.57,1.642694e+09,1.650312e+09,1.650658e+09,NaN